services:
  api:
    image: cayde879/new-rust-indexer-api:latest
    platform: linux/arm64
    restart: unless-stopped
    environment:
      CLICKHOUSE_URL: "http://clickhouse:8123" # Use container name
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD}"
      CLICKHOUSE_DATABASE: "${CLICKHOUSE_DATABASE}"
      REDIS_URL: "redis://35.95.74.27:6379/"
    ports:
      - 3001:3001
    networks:
      - shared

networks:
  shared:
    external: true
